# Generated by Django 2.1.15 on 2022-04-26 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='company_story',
            name='article',
        ),
        migrations.AddField(
            model_name='company_story',
            name='p1',
            field=models.CharField(blank=True, max_length=250),
        ),
        migrations.AddField(
            model_name='company_story',
            name='p2',
            field=models.CharField(blank=True, max_length=250),
        ),
        migrations.AlterField(
            model_name='company_story',
            name='image',
            field=models.ImageField(upload_to='uplaod/images'),
        ),
    ]
