# Generated by Django 2.1.15 on 2022-04-26 23:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_app', '0005_auto_20220426_2317'),
    ]

    operations = [
        migrations.AlterField(
            model_name='successstories',
            name='story_title',
            field=models.CharField(max_length=250),
        ),
    ]
