# Generated by Django 2.1.15 on 2022-04-26 23:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core_app', '0006_auto_20220426_2323'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='SuccessStories',
            new_name='Stories',
        ),
    ]
