# Generated by Django 2.1.15 on 2022-05-07 17:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core_app', '0014_auto_20220507_1711'),
    ]

    operations = [
        migrations.RenameField(
            model_name='team',
            old_name='firstm_member',
            new_name='first_member',
        ),
    ]
