# Generated by Django 4.0.4 on 2022-05-09 12:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core_app', '0016_alter_company_story_id_alter_contactus_id_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ContactUs',
        ),
        migrations.DeleteModel(
            name='Service',
        ),
    ]
